server:
  port: ${PORT:9091}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: test-bot-project
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:u0_a325}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
  task:
    scheduling:
      thread-name-prefix: sched-
      pool:
        size: 4

app:
  timezone: ${APP_TIMEZONE:Europe/Kyiv}
  schedule:
    clear-context-cron: ${CLEAR_CONTEXT_CRON:0 0 2 * * *}
    daily-summary-cron: ${DAILY_SUMMARY_CRON:0 30 21 * * *}
    monthly-summary-cron: ${MONTHLY_SUMMARY_CRON:0 45 21 * * *}

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
    api-base-url: ${TELEGRAM_BOT_API_BASE_URL}
    need-auto-transcribe: ${AUTO_TRANSCRIBE:false}
    news-chat-id: ${NEWS_CHAT_ID}
    downloader-endpoint: ${DOWNLOADER_ENDPOINT}

ai:
  api-base-url: ${AI_API_BASE_URL}
  api-key: ${AI_API_KEY}
  api-key-secondary: ${AI_API_KEY_2}
  enable-secondary: ${ENABLE_SECONDARY:false}
  default-model: ${AI_DEFAULT_MODEL}
  system-prompt: ${AI_SYSTEM_PROMPT}

transcription-model: ${TRANSCRIPTION_MODEL}
tts-model: ${TTS_MODEL:gemini-3.1-flash-tts-preview}
tts-voice: ${TTS_VOICE:Puck}
